# Generated by Django 6.0.5 on 2026-05-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applied_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.promocode', verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая цена со скидкой'),
        ),
    ]
